"""add alternatives_json to detected_symbols

Revision ID: 160265864122
Revises: a04c69cf5072
Create Date: 2026-03-25 10:40:39.866133

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "160265864122"
down_revision: str | Sequence[str] | None = "a04c69cf5072"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "detected_symbols",
        sa.Column("alternatives_json", sa.String(length=2000), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("detected_symbols", "alternatives_json")
    # ### end Alembic commands ###
