"""ui improvements: storage_location, drop label_addition and general_item tables

Revision ID: 1ee4e48e5658
Revises: b07fca376e34
Create Date: 2026-03-19 21:21:27.269869

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "1ee4e48e5658"
down_revision: str | Sequence[str] | None = "b07fca376e34"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("general_item_types")
    op.drop_table("general_item_details")
    # Migrate label_addition data into particularities before dropping the column
    op.execute("""
        UPDATE instrument_details
        SET particularities = label_addition
        WHERE label_addition IS NOT NULL AND (particularities IS NULL OR particularities = '')
    """)
    op.execute("""
        UPDATE instrument_details
        SET particularities = particularities || ' | ' || label_addition
        WHERE label_addition IS NOT NULL AND particularities IS NOT NULL AND particularities != ''
    """)
    op.drop_column("instrument_details", "label_addition")
    op.add_column(
        "inventory_items",
        sa.Column("storage_location", sa.String(length=200), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inventory_items", "storage_location")
    op.add_column(
        "instrument_details",
        sa.Column("label_addition", sa.VARCHAR(length=100), nullable=True),
    )
    op.create_table(
        "general_item_details",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("item_id", sa.INTEGER(), nullable=False),
        sa.Column("general_item_type_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["general_item_type_id"],
            ["general_item_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["inventory_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id"),
    )
    op.create_table(
        "general_item_types",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("label", sa.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    # ### end Alembic commands ###
