"""add staff_removal_symbol_padding to config

Revision ID: 2cbdde7a68e8
Revises: a0d2e422b2ff
Create Date: 2026-03-28 11:18:04.160890

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cbdde7a68e8"
down_revision: str | Sequence[str] | None = "a0d2e422b2ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scanner_config",
        sa.Column(
            "staff_removal_symbol_padding",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scanner_config", "staff_removal_symbol_padding")
    # ### end Alembic commands ###
