"""add deskew_method to scanner_config

Revision ID: 2d756303e6cc
Revises: cbfa11db09c9
Create Date: 2026-03-26 20:39:19.621617

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d756303e6cc"
down_revision: str | Sequence[str] | None = "cbfa11db09c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scanner_config",
        sa.Column(
            "deskew_method",
            sa.String(length=20),
            nullable=False,
            server_default="projection",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scanner_config", "deskew_method")
    # ### end Alembic commands ###
