"""add dewarp config fields

Revision ID: 2e9b06b45cda
Revises: e4ea2d88c533
Create Date: 2026-03-27 09:56:05.690163

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e9b06b45cda"
down_revision: str | Sequence[str] | None = "e4ea2d88c533"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scanner_config",
        sa.Column(
            "dewarp_enabled", sa.Boolean(), nullable=False, server_default=sa.text("0")
        ),
    )
    op.add_column(
        "scanner_config",
        sa.Column(
            "dewarp_smoothing",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("50"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scanner_config", "dewarp_smoothing")
    op.drop_column("scanner_config", "dewarp_enabled")
    # ### end Alembic commands ###
