"""add category and catalog_number to scan_projects

Revision ID: 41f91513cb32
Revises: 2cbdde7a68e8
Create Date: 2026-03-28 14:32:27.734507

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41f91513cb32"
down_revision: str | Sequence[str] | None = "2cbdde7a68e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scan_projects", sa.Column("category", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "scan_projects", sa.Column("catalog_number", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scan_projects", "catalog_number")
    op.drop_column("scan_projects", "category")
    # ### end Alembic commands ###
