"""add filtered fields to detected symbols

Revision ID: 74b05fa3a239
Revises: 41f91513cb32
Create Date: 2026-03-30 12:25:39.979078

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74b05fa3a239"
down_revision: str | Sequence[str] | None = "41f91513cb32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "detected_symbols",
        sa.Column("filtered", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "detected_symbols",
        sa.Column("filter_reason", sa.String(length=200), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("detected_symbols", "filter_reason")
    op.drop_column("detected_symbols", "filtered")
    # ### end Alembic commands ###
