"""add hairpin_min_hitbox_width_factor

Revision ID: 7e48d0eb1385
Revises: eae012c0e31f
Create Date: 2026-04-04 22:29:41.175795

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e48d0eb1385"
down_revision: str | Sequence[str] | None = "eae012c0e31f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scanner_config",
        sa.Column(
            "hairpin_min_hitbox_width_factor",
            sa.Float(),
            nullable=False,
            server_default="3.0",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scanner_config", "hairpin_min_hitbox_width_factor")
    # ### end Alembic commands ###
