"""add hairpin_min_confidence to scanner_config

Revision ID: 9f7b8dfd2010
Revises: 7e48d0eb1385
Create Date: 2026-04-05 18:12:53.186347

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f7b8dfd2010"
down_revision: str | Sequence[str] | None = "7e48d0eb1385"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scanner_config",
        sa.Column(
            "hairpin_min_confidence", sa.Float(), nullable=False, server_default="0.3"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scanner_config", "hairpin_min_confidence")
    # ### end Alembic commands ###
