"""add height_in_lines to symbol_variants

Revision ID: a04c69cf5072
Revises: c91a3d75630f
Create Date: 2026-03-25 00:31:37.366142

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a04c69cf5072"
down_revision: str | Sequence[str] | None = "c91a3d75630f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
