"""add line_thickness to staves and staff_removal_thickness_pct to config

Revision ID: a0d2e422b2ff
Revises: 2e9b06b45cda
Create Date: 2026-03-27 19:08:37.334942

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0d2e422b2ff"
down_revision: str | Sequence[str] | None = "2e9b06b45cda"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "detected_staves", sa.Column("line_thickness", sa.Integer(), nullable=True)
    )
    op.add_column(
        "scanner_config",
        sa.Column(
            "staff_removal_thickness_pct",
            sa.Integer(),
            nullable=False,
            server_default="100",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scanner_config", "staff_removal_thickness_pct")
    op.drop_column("detected_staves", "line_thickness")
    # ### end Alembic commands ###
