"""add source_line_spacing to symbol_variants

Revision ID: af1199d3ac7f
Revises: 160265864122
Create Date: 2026-03-25 20:54:22.754414

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af1199d3ac7f"
down_revision: str | Sequence[str] | None = "160265864122"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "symbol_variants", sa.Column("source_line_spacing", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("symbol_variants", "source_line_spacing")
    # ### end Alembic commands ###
