"""add scanner tables

Revision ID: c91a3d75630f
Revises: 1ee4e48e5658
Create Date: 2026-03-24 18:08:47.689743

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "c91a3d75630f"
down_revision: str | Sequence[str] | None = "1ee4e48e5658"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("composer", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "symbol_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("musicxml_element", sa.Text(), nullable=True),
        sa.Column("lilypond_token", sa.String(length=50), nullable=True),
        sa.Column("is_seed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "scan_parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("part_name", sa.String(length=200), nullable=False),
        sa.Column("part_order", sa.Integer(), nullable=False),
        sa.Column("clef_hint", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["scan_projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "symbol_variants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("image_path", sa.String(length=500), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("feature_vector_json", sa.Text(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["template_id"], ["symbol_templates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sheet_music_scans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("image_path", sa.String(length=500), nullable=False),
        sa.Column("processed_image_path", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("adjustments_json", sa.Text(), nullable=True),
        sa.Column("pipeline_config_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["part_id"], ["scan_parts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "detected_staves",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scan_id", sa.Integer(), nullable=False),
        sa.Column("staff_index", sa.Integer(), nullable=False),
        sa.Column("y_top", sa.Integer(), nullable=False),
        sa.Column("y_bottom", sa.Integer(), nullable=False),
        sa.Column("line_positions_json", sa.Text(), nullable=False),
        sa.Column("line_spacing", sa.Float(), nullable=False),
        sa.Column("clef", sa.String(length=20), nullable=True),
        sa.Column("key_signature", sa.String(length=50), nullable=True),
        sa.Column("time_signature", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["sheet_music_scans.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "detected_symbols",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("snippet_path", sa.String(length=500), nullable=True),
        sa.Column("position_on_staff", sa.Integer(), nullable=True),
        sa.Column("sequence_order", sa.Integer(), nullable=False),
        sa.Column("matched_symbol_id", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("user_verified", sa.Boolean(), nullable=False),
        sa.Column("user_corrected_symbol_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["matched_symbol_id"], ["symbol_templates.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"], ["detected_staves.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_corrected_symbol_id"], ["symbol_templates.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("detected_symbols")
    op.drop_table("detected_staves")
    op.drop_table("sheet_music_scans")
    op.drop_table("symbol_variants")
    op.drop_table("scan_parts")
    op.drop_table("symbol_templates")
    op.drop_table("scan_projects")
    # ### end Alembic commands ###
