"""add scanner_config table

Revision ID: cbfa11db09c9
Revises: 4ba93c0f6d82
Create Date: 2026-03-26 10:17:18.768846

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbfa11db09c9"
down_revision: str | Sequence[str] | None = "4ba93c0f6d82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scanner_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("confidence_threshold", sa.Float(), nullable=False),
        sa.Column("matching_method", sa.String(length=30), nullable=False),
        sa.Column("multi_scale_enabled", sa.Boolean(), nullable=False),
        sa.Column("multi_scale_range", sa.Float(), nullable=False),
        sa.Column("multi_scale_steps", sa.Integer(), nullable=False),
        sa.Column("edge_matching_enabled", sa.Boolean(), nullable=False),
        sa.Column("canny_low", sa.Integer(), nullable=False),
        sa.Column("canny_high", sa.Integer(), nullable=False),
        sa.Column("staff_removal_before_matching", sa.Boolean(), nullable=False),
        sa.Column("masked_matching_enabled", sa.Boolean(), nullable=False),
        sa.Column("mask_threshold", sa.Integer(), nullable=False),
        sa.Column("nms_iou_threshold", sa.Float(), nullable=False),
        sa.Column("nms_method", sa.String(length=20), nullable=False),
        sa.Column("adaptive_threshold_block_size", sa.Integer(), nullable=False),
        sa.Column("adaptive_threshold_c", sa.Integer(), nullable=False),
        sa.Column("morphology_kernel_size", sa.Integer(), nullable=False),
        sa.Column("auto_verify_confidence", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scanner_config")
    # ### end Alembic commands ###
