"""add text_masking_min_confidence to scanner_config

Revision ID: da1809c92386
Revises: 48ed92caccc1
Create Date: 2026-04-04 15:37:49.386071

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da1809c92386"
down_revision: str | Sequence[str] | None = "48ed92caccc1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scanner_config",
        sa.Column(
            "text_masking_min_confidence",
            sa.Integer(),
            nullable=False,
            server_default="30",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scanner_config", "text_masking_min_confidence")
    # ### end Alembic commands ###
