"""add corrected_image_path to sheet_music_scans

Revision ID: e4ea2d88c533
Revises: 2d756303e6cc
Create Date: 2026-03-26 20:42:30.314725

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4ea2d88c533"
down_revision: str | Sequence[str] | None = "2d756303e6cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sheet_music_scans",
        sa.Column("corrected_image_path", sa.String(length=500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sheet_music_scans", "corrected_image_path")
    # ### end Alembic commands ###
