"""add staff_margin_top and staff_margin_bottom to scanner_config

Revision ID: e8e7aacfc5e9
Revises: 9f7b8dfd2010
Create Date: 2026-04-08 09:47:28.276827

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8e7aacfc5e9"
down_revision: str | Sequence[str] | None = "9f7b8dfd2010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scanner_config",
        sa.Column("staff_margin_top", sa.Float(), nullable=False, server_default="4.0"),
    )
    op.add_column(
        "scanner_config",
        sa.Column(
            "staff_margin_bottom", sa.Float(), nullable=False, server_default="4.0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scanner_config", "staff_margin_bottom")
    op.drop_column("scanner_config", "staff_margin_top")
    # ### end Alembic commands ###
