"""add hairpin_min_width_factor to scanner_config

Revision ID: eae012c0e31f
Revises: da1809c92386
Create Date: 2026-04-04 20:37:42.205597

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eae012c0e31f"
down_revision: str | Sequence[str] | None = "da1809c92386"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scanner_config",
        sa.Column(
            "hairpin_min_width_factor", sa.Float(), nullable=False, server_default="3.0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scanner_config", "hairpin_min_width_factor")
    # ### end Alembic commands ###
